import uuid
from datetime import datetime, timezone
from enum import Enum

from sqlalchemy import Column, String, Integer, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID

from database import base

# Enums
class MovementStatus(str, Enum):
    pending = "Pending"
    open = "Open"
    activated = "Activated"
    cancelled = "Cancelled"

class AttendanceStatus(str, Enum):
    register = "register"
    attend = "attend"
    miss = "miss"

# Database Models
# TODO : Need Checking for database structure

# User Table
class User(base):
    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    address = Column(String, unique=True, nullable=True)
    reputation = Column(Integer, default=0, nullable=False)
    participations = relationship("Participant", back_populates="user")

# Movement Table
class Movement(base):
    __tablename__ = "movement"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # On-chain attributes 
    # These attribute can be null because the data might be created before the transaction is confirmed.
    # onchain_id -> movementId generated by smart contract
    onchain_id = Column(Integer, unique=True, index=True, nullable=True)
    # ipfs_id -> IPFS string hash
    ipfs_id = Column(String, unique=True, nullable=True)

    organizer_id = Column(UUID(as_uuid=True), ForeignKey('users.id'), nullable=False)
    title = Column(String, nullable=False)
    due = Column(DateTime(timezone=True), nullable=False)
    status = Column(String, default=MovementStatus.pending.value, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=lambda : datetime.now(timezone.utc))

    participants = relationship("Participant", back_populates="movement")
    organizer = relationship("User", foreign_keys=[organizer_id])
    

# Participant Table
class Participant(base):
    __tablename__ = "participant"

    movement_id = Column(UUID(as_uuid=True), ForeignKey('movements.id'), primary_key=True)
    participant_id = Column(UUID(as_uuid=True), ForeignKey('users.id'), primary_key=True)
    attendance_status = Column(String, default=AttendanceStatus.register.value, nullable=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=lambda : datetime.now(timezone.utc))

    movement = relationship("Movement", back_populates="participants")
    user = relationship("User", back_populates="participations")